# info
site:
  title: NoLogger
  author: Kwangmin-Kim
  email: 1721046@gmail.com

# logging
# logging.level.root: info
logging.level.root: debug

# spring
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/local/schema-local.sql
      data-locations: classpath:/sql/local/data-local.sql