DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS CATEGORY (
    ID VARCHAR2(30),
    PARENT_ID VARCHAR2(30),
    IS_PAGE_CATEGORY BOOLEAN,
    ORDER_NUMBER TINYINT,
    TITLE VARCHAR2(256),
    URL VARCHAR2(256),
    VISIBLE BOOLEAN,
    CREATED_AT DATE,
    MODIFIED_AT DATE
);
CREATE SEQUENCE IF NOT EXISTS CATEGORY_SEQUENCE;