DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS ARTICLE (
    ID VARCHAR2(256),
    WRITER VARCHAR2(256),
    TITLE VARCHAR2(256),
    CATEGORY VARCHAR2(256),
    CONTENT CLOB,
    CREATED_AT DATE,
    MODIFIED_AT DATE
);
CREATE SEQUENCE IF NOT EXISTS ARTICLE_SEQUENCE;

CREATE TABLE IF NOT EXISTS CATEGORY (
    ID VARCHAR2(256),
    CREATED_AT DATE,
    MODIFIED_AT DATE
);

CREATE TABLE IF NOT EXISTS ADMIN_MEMBER (
    ID VARCHAR2(256),
    ACCOUNT VARCHAR2(256),
    PASSWORD VARCHAR2(256),
    PIN_NUMBER VARCHAR2(256),
    IP_ADDRESS1 VARCHAR2(256),
    IP_ADDRESS2 VARCHAR2(256),
    IP_ADDRESS3 VARCHAR2(256),
    CREATED_AT DATE,
    MODIFIED_AT DATE
);
CREATE SEQUENCE IF NOT EXISTS ADMIN_MEMBER_SEQUENCE;