DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS CATEGORY (
    ID VARCHAR2(30),
    PARENT_ID VARCHAR2(30),
    ORDER_NUMBER TINYINT,
    IS_ROOT BOOLEAN,
    URL VARCHAR2(256),
    TITLE VARCHAR2(256),
    CREATED_AT DATE,
    MODIFIED_AT DATE
);
CREATE SEQUENCE IF NOT EXISTS CATEGORY_SEQUENCE;

CREATE TABLE IF NOT EXISTS PAGE (
    ID VARCHAR2(30),
    CATEGORY_ID VARCHAR2(30),
    TITLE VARCHAR2(256),
    CONTENT CLOB,
    CREATED_AT DATE,
    MODIFIED_AT DATE
);
CREATE SEQUENCE IF NOT EXISTS PAGE_SEQUENCE;